  USE WISE_STAGING
  GO
  
--=======================================================================================================================================
--||Author		: Juanda Nico Hasibuan
--||Create date	: 23-11-2021
--||Description	: Untuk Mendapatkan Status Maindealer
--|| History	: 
--|| Version    : v1.0.20211123
--||-------------------------------------------------------------------------------------------------------------------------------------
--|| Date			| Type		| Version			| Name					|No Project				| Description												 
--||-------------------------------------------------------------------------------------------------------------------------------------- 
--|| 23-11-2021		| Create 	| v1.0.20211123		| Juanda Nico Hasibuan	|BR/2021/JUL/MKT/001    | API Marketplace & Main Dealer - Phase Main Dealer​
--======================================================================================================================================= 
  
CREATE PROCEDURE [dbo].[spMKT_MAINDEALER_GET_STATUS](  
@poStatusOut VARCHAR(100) OUTPUT,  
@poIdPartnerOut VARCHAR(20) OUTPUT,   
@poStatusCode VARCHAR(100) OUTPUT,  
@poMessage VARCHAR(100) OUTPUT,  
@poNoPOOut VARCHAR(50) OUTPUT,  
@poTglPOOut DATE OUTPUT,  
@poDPOut VARCHAR(100) OUTPUT,  
@poTenorOut VARCHAR(100) OUTPUT,
@poOrderId VARCHAR(100) OUTPUT,
@poDealerName  VARCHAR(200) OUTPUT,
@pofullName   VARCHAR(200) OUTPUT,
@poAgrmntNo   VARCHAR(50) OUTPUT,
@poInstalmentAmt  VARCHAR(100) OUTPUT ,
@poTransactionId VARCHAR(100) OUTPUT
  
)  
AS  
DECLARE  
@piUSR_CRT VARCHAR (50)='',  
@ORDER_ID VARCHAR (30),  
@ID_PARTNER VARCHAR (20),  
@ORDER_DT DATETIME, -- GATEDATE()  
@PO_STATUS VARCHAR(100),  
@PHONE_NUMBER VARCHAR(24),  
@STATUS_DT DATE,  
@MAX_SEQ_NO INT,  
@DATA_INQUIRY VARCHAR(MAX),  
@MESSAGE VARCHAR(100),  
@STATUS_CODE VARCHAR(100),  
@STATUS_DESC VARCHAR(100),   
@idNo VARCHAR(50),  
@poNoPO VARCHAR(50),  
@poTglPO DATE,  
@poDP VARCHAR(100),  
@poTenor VARCHAR(100),
@piPARTNER_ID varchar(100),
@TRANSACTION_ID VARCHAR(100) ,
@DEALER_NAME  VARCHAR(200)  ,
@FULL_NAME   VARCHAR(200)  ,
@AGRMNT_NO   VARCHAR(50)  ,
@INSTALMENT_AMT  VARCHAR(100)  

 
  
BEGIN TRY -- AWAL  
  SET NOCOUNT ON  
  SET ANSI_WARNINGS OFF   
  	
	BEGIN	 
		 SELECT
		 @piPARTNER_ID                 = PARTNER_ID
		,@ORDER_ID                     = ORDER_ID  
		,@piUSR_CRT					   = ID_NAME
		FROM ##listRowMainDStatChk
	END
  
  INSERT INTO WISE_STAGING.DBO.LOG_JOB_MARKETPLACE (PROC_NAME, DATE_PROCESSED, ERR_MESSAGE, ERR_LINE, ERR_NUMBER)  
   VALUES ('spMKT_MAINDEALER_GET_STATUS', GETDATE(), 'START', NULL, NULL)  
  
DECLARE @errorCodeList TABLE (STATUS_CODE VARCHAR(50), MSG VARCHAR(100))  
 INSERT INTO @errorCodeList(STATUS_CODE, MSG)  
  SELECT RESPONSE_CODE,RESPONSE_MESSAGE   
    FROM [dbo].[M_MKT_MAINDEALER_RESPONSECODE]  with (nolock) 
 
    
  
 SELECT @MAX_SEQ_NO=MAX([SEQUENCE])  
  FROM T_MKT_MARKETPLACE_STATUS TMKT  with (nolock)
  WHERE TMKT.ORDER_ID = @ORDER_ID  
  
  SET @poNoPO = null
SET @poDP = null
SET @poTglPO = null
SET @poTenor = null

  SELECT @ID_PARTNER = TMKTCQ.PARTNER_ID, @PO_STATUS = MMKT.STATUS,@PHONE_NUMBER = TMKTCQ.PHONE_NUMBER 
	, @AGRMNT_NO=TMKTCQ.AGRMNT_NO, @INSTALMENT_AMT=TMKTCQ.INSTALMENT_AMT, @TRANSACTION_ID=TRANSACTION_ID, @DEALER_NAME=MMMP.NAME_MARKETPLACE, @FULL_NAME=FULL_NAME
	,@poDP=TMKTCQ.PO_DP, @poNoPO=TMKTCQ.PO_NO, @poTglPO=TMKTCQ.PO_DATE, @poTenor=TMKTCQ.PO_TENOR
    FROM T_MKT_MARKETPLACE_ACQ TMKTCQ with (nolock) 
    LEFT JOIN M_MKT_MARKETPLACE_STATUS MMKT ON TMKTCQ.ID_STATUS=MMKT.ID_STATUS
	LEFT JOIN M_MKT_MARKETPLACE_PARTNER MMMP ON TMKTCQ.PARTNER_ID=MMMP.ID_MARKETPLACE
   WHERE TMKTCQ.PARTNER_ID=ISNULL(@piPARTNER_ID,'X') AND TMKTCQ.ORDER_ID = ISNULL(@ORDER_ID,'X')  
 
SELECT @idNo = ID_NO FROM T_MKT_MARKETPLACE_ACQ WHERE ORDER_ID = ISNULL(@ORDER_ID,'X')

 
    
 IF 	EXISTS (SELECT 1 FROM M_MKT_MARKETPLACE_PARTNER with (nolock) WHERE ID_MARKETPLACE = ISNULL(@piPARTNER_ID,'X') AND FLAG_MASTER_PARTNER='Main_Dealer' ) 
	BEGIN		
		IF EXISTS (SELECT 1 FROM T_MKT_MARKETPLACE_ACQ with (nolock) WHERE ORDER_ID = ISNULL(@ORDER_ID,'X') )
		BEGIN  
			IF EXISTS (SELECT 1 FROM T_MKT_MARKETPLACE_ACQ WHERE PARTNER_ID=ISNULL(@piPARTNER_ID,'X') AND ORDER_ID = ISNULL(@ORDER_ID,'X') )
			BEGIN	  
				 /*SUKSESS*/
				SET @STATUS_CODE='00'
				SET @MESSAGE=(SELECT MSG FROM @errorCodeList WHERE STATUS_CODE=@STATUS_CODE)				
				SET @DATA_INQUIRY=CONVERT(VARCHAR,@ID_PARTNER)+','+CONVERT(VARCHAR,@ORDER_ID)+','+CONVERT(VARCHAR,@PHONE_NUMBER)+','+CONVERT(VARCHAR,@PO_STATUS)+','+CONVERT(VARCHAR,@STATUS_DT)+','+ISNULL(CONVERT(VARCHAR,@poNoPO), '')+','+ISNULL(CONVERT(VARCHAR,@poDP), '')+','+ISNULL(CONVERT(VARCHAR,@poTglPO), '')+','+ISNULL(CONVERT(VARCHAR,@poTenor), '')
				INSERT INTO T_MKT_MARKETPLACE_STATUS_REQ (ORDER_ID, PARTNER_ID, RESPONSE_CODE, [MESSAGE], DATA_INQUIRY, DTM_RESPONSE, DTM_CRT, USR_CRT, USR_UPD, DTM_UPD )
				SELECT @ORDER_ID, @piPARTNER_ID, @STATUS_CODE, @MESSAGE, @DATA_INQUIRY,  GETDATE(), GETDATE(), @piUSR_CRT, @piUSR_CRT, GETDATE()

				--OUTPUT RESULT  
				SELECT @poStatusOut = @PO_STATUS, @poIdPartnerOut = @piPARTNER_ID, @poOrderId=@ORDER_ID 
					  ,@poMessage=@MESSAGE,@poStatusCode=@STATUS_CODE,   @poNoPOOut= @poNoPO, @poTglPOOut = @poTglPO, @poDPOut= @poDP, @poTenorOut=@poTenor
					  ,@poAgrmntNo=@AGRMNT_NO, @poInstalmentAmt=@INSTALMENT_AMT, @poTransactionId=@TRANSACTION_ID, @poDealerName=@DEALER_NAME, @pofullName=@FULL_NAME 
			END
			ELSE
			BEGIN
				/*Error - Order Id tidak terdaftar*/				 
				SET @STATUS_CODE='07'
				SET @MESSAGE=(SELECT MSG FROM @errorCodeList WHERE STATUS_CODE=@STATUS_CODE)
				SET @DATA_INQUIRY=CONVERT(VARCHAR,@ID_PARTNER)+','+CONVERT(VARCHAR,@ORDER_ID)+','+CONVERT(VARCHAR,@PHONE_NUMBER)+','+CONVERT(VARCHAR,@PO_STATUS)+','+CONVERT(VARCHAR,@STATUS_DT)+','+ISNULL(CONVERT(VARCHAR,@poNoPO), '')+','+ISNULL(CONVERT(VARCHAR,@poDP), '')+','+ISNULL(CONVERT(VARCHAR,@poTglPO), '')+','+ISNULL(CONVERT(VARCHAR,@poTenor), '')
				INSERT INTO T_MKT_MARKETPLACE_STATUS_REQ (ORDER_ID, PARTNER_ID, RESPONSE_CODE, [MESSAGE], DATA_INQUIRY, DTM_RESPONSE, DTM_CRT, USR_CRT, USR_UPD, DTM_UPD )
				SELECT @ORDER_ID, @piPARTNER_ID, @STATUS_CODE, @MESSAGE, @DATA_INQUIRY,  GETDATE(), GETDATE(), @piUSR_CRT, @piUSR_CRT, GETDATE()
  
				--OUTPUT RESULT  
				SELECT @poStatusOut = @PO_STATUS, @poIdPartnerOut = @piPARTNER_ID, @poOrderId=@ORDER_ID 
					  ,@poMessage=@MESSAGE,@poStatusCode=@STATUS_CODE, @poNoPOOut= @poNoPO, @poTglPOOut = @poTglPO, @poDPOut= @poDP, @poTenorOut=@poTenor
					  ,@poAgrmntNo=@AGRMNT_NO, @poInstalmentAmt=@INSTALMENT_AMT, @poTransactionId=@TRANSACTION_ID, @poDealerName=@DEALER_NAME, @pofullName=@FULL_NAME
			END
		END
		ELSE
		/*Error - Order Id tidak terdaftar*/
		BEGIN 
			SET @STATUS_CODE='07'
			SET @MESSAGE=(SELECT MSG FROM @errorCodeList WHERE STATUS_CODE=@STATUS_CODE)			
			SET @DATA_INQUIRY=CONVERT(VARCHAR,@ID_PARTNER)+','+CONVERT(VARCHAR,@ORDER_ID)+','+CONVERT(VARCHAR,@PHONE_NUMBER)+','+CONVERT(VARCHAR,@PO_STATUS)+','+CONVERT(VARCHAR,@STATUS_DT)+','+ISNULL(CONVERT(VARCHAR,@poNoPO), '')+','+ISNULL(CONVERT(VARCHAR,@poDP), '')+','+ISNULL(CONVERT(VARCHAR,@poTglPO), '')+','+ISNULL(CONVERT(VARCHAR,@poTenor), '')
			INSERT INTO T_MKT_MARKETPLACE_STATUS_REQ (ORDER_ID, PARTNER_ID, RESPONSE_CODE, [MESSAGE], DATA_INQUIRY, DTM_RESPONSE, DTM_CRT, USR_CRT, USR_UPD, DTM_UPD )
			SELECT @ORDER_ID, @piPARTNER_ID, @STATUS_CODE, @MESSAGE, @DATA_INQUIRY,  GETDATE(), GETDATE(), @piUSR_CRT, @piUSR_CRT, GETDATE()
  
		  --OUTPUT RESULT  
			SELECT @poStatusOut = @PO_STATUS, @poIdPartnerOut = @piPARTNER_ID, @poOrderId=@ORDER_ID 
					  ,@poMessage=@MESSAGE,@poStatusCode=@STATUS_CODE, @poNoPOOut= @poNoPO, @poTglPOOut = @poTglPO, @poDPOut= @poDP, @poTenorOut=@poTenor
					  ,@poAgrmntNo=@AGRMNT_NO, @poInstalmentAmt=@INSTALMENT_AMT, @poTransactionId=@TRANSACTION_ID, @poDealerName=@DEALER_NAME, @pofullName=@FULL_NAME
  
		END

	END
	ELSE
	/*Error - Partner Id tidak terdaftar*/ 
	BEGIN	 
			SET @STATUS_CODE='08'
			SET @MESSAGE=(SELECT MSG FROM @errorCodeList WHERE STATUS_CODE=@STATUS_CODE)			
			SET @DATA_INQUIRY=CONVERT(VARCHAR,@ID_PARTNER)+','+CONVERT(VARCHAR,@ORDER_ID)+','+CONVERT(VARCHAR,@PHONE_NUMBER)+','+CONVERT(VARCHAR,@PO_STATUS)+','+CONVERT(VARCHAR,@STATUS_DT)+','+ISNULL(CONVERT(VARCHAR,@poNoPO), '')+','+ISNULL(CONVERT(VARCHAR,@poDP), '')+','+ISNULL(CONVERT(VARCHAR,@poTglPO), '')+','+ISNULL(CONVERT(VARCHAR,@poTenor), '')
			INSERT INTO T_MKT_MARKETPLACE_STATUS_REQ (ORDER_ID, PARTNER_ID, RESPONSE_CODE, [MESSAGE], DATA_INQUIRY, DTM_RESPONSE, DTM_CRT, USR_CRT, USR_UPD, DTM_UPD )
			SELECT @ORDER_ID, @piPARTNER_ID, @STATUS_CODE, @MESSAGE, @DATA_INQUIRY,  GETDATE(), GETDATE(), @piUSR_CRT, @piUSR_CRT, GETDATE()
  
			--OUTPUT RESULT  
			SELECT @poStatusOut = @PO_STATUS, @poIdPartnerOut = @piPARTNER_ID, @poOrderId=@ORDER_ID 
					  ,@poMessage=@MESSAGE,@poStatusCode=@STATUS_CODE,  @poNoPOOut= @poNoPO, @poTglPOOut = @poTglPO, @poDPOut= @poDP, @poTenorOut=@poTenor
					  ,@poAgrmntNo=@AGRMNT_NO, @poInstalmentAmt=@INSTALMENT_AMT, @poTransactionId=@TRANSACTION_ID, @poDealerName=@DEALER_NAME, @pofullName=@FULL_NAME
	END  
   
   
   INSERT INTO WISE_STAGING.DBO.LOG_JOB_MARKETPLACE (PROC_NAME, DATE_PROCESSED, ERR_MESSAGE, ERR_LINE, ERR_NUMBER)  
   VALUES ('spMKT_MAINDEALER_GET_STATUS', GETDATE(), 'END', NULL, NULL)  
  
END TRY  
  
BEGIN CATCH
  --OUTPUT RESULT  
   DECLARE
	@ERRMSG	        VARCHAR(500),
    @ERRSEVERITY	INT,
	@ERRSTATE		INT

	SELECT @ERRMSG = ERROR_MESSAGE(),
		   @ERRSEVERITY = ERROR_SEVERITY(),
	 	   @ERRSTATE = ERROR_STATE()

	INSERT INTO WISE_STAGING.DBO.LOG_JOB_MARKETPLACE (PROC_NAME, DATE_PROCESSED, ERR_MESSAGE, ERR_LINE, ERR_NUMBER)
    VALUES ('spMKT_MAINDEALER_GET_STATUS', GETDATE(), 'ERROR : '+ISNULL(@ERRMSG,'-'), NULL, NULL)
	
	SET @STATUS_CODE='30'
	SET @MESSAGE=(SELECT MSG FROM @errorCodeList WHERE STATUS_CODE=@STATUS_CODE)	

	RAISERROR(@ERRMSG, @ERRSEVERITY, @ERRSTATE)
    SELECT @poStatusOut = '', @poIdPartnerOut = '', @poOrderId=@ORDER_ID, @poMessage=@MESSAGE,@poStatusCode=@STATUS_CODE , @poNoPOOut= '', @poTglPOOut = '', @poDPOut= '', @poTenorOut=''
 

END CATCH 
  
  